@startuml
actor User
participant Ui
participant InternTrack
participant Parser
participant ApplicationList
participant Storage

User -> Ui : edit INDEX [FIELDS]
Ui -> InternTrack : handleEditCommand()
InternTrack -> Parser : parseEditIndex()
InternTrack -> Parser : parseEditDetails()
InternTrack -> ApplicationList : editApplication()
InternTrack -> Storage : saveApplications()
InternTrack -> Ui : printEditApplication()

@enduml
