@startuml
actor User
participant Ui
participant InternTrack
participant Parser
participant SummaryCommand

User -> Ui : summary
Ui -> InternTrack : handleSummaryCommand()
InternTrack -> Parser : parseSummaryCommand()
Parser -> InternTrack

InternTrack -> SummaryCommand : execute(applications)
SummaryCommand -> InternTrack

InternTrack -> Ui : printSummaryReport()
Ui -> User
@enduml